### ISSUE TITLE
AERO_UI_TC18 : Operators >> Operators >> Add a Operator - Unable to Create Operator

### ISSUE THREAD

**Issue by akshitmahajan** [openskies-sh/aerobridge#12]
Cause - Missing Dropdown fields for Operational authorizations* & Authorized activities*
Severity - Blocker

<img width="819" alt="Screen Shot 2021-06-16 at 2 33 42 PM" src="https://user-images.githubusercontent.com/6078058/122191057-0518a800-ceb0-11eb-9fdd-bad95fbd993f.png">

<img width="516" alt="Screen Shot 2021-06-16 at 2 32 18 PM" src="https://user-images.githubusercontent.com/6078058/122190740-b79c3b00-ceaf-11eb-999b-e56806728d2f.png">

**Comment by hrishiballal** [comment]
Thanks for this, this has to do with the loading of the fixture. I have reset the database and reloaded the [fixture](https://github.com/openskies-sh/aerobridge/blob/master/registry/defaultregistrydata.json) with the default data now. 

I have tested it and a "India Drone Co." in the database. Thanks for this!

![image](https://user-images.githubusercontent.com/1588744/122389605-02c65480-cf69-11eb-8031-c3d62869b171.png)

**Comment by akshitmahajan** [comment]
Where are the Operational authorizations* SORA V2 and SORA coming from?

**Comment by hrishiballal** [comment]
These are hard coded in the database (we can use the Django Admin panel to add additional ones). But basically certain operators will have certain capabilities and the Civil Aviation Authority (DGCA in India) will issue authorizations to operatrors. E.g. they may say we have verified that this operator has night vision cameras so we will allow them to operate in the night. These are operational authorizations and this field links them to the operator. Hope this helps. As far as Aerobridge is concerned, this is just a text field but we may in the future add facility to store documentation re each authorization.
