### ISSUE TITLE
AERO_UI_TC13 : General - Cancel button missing on every page with save/update button

### ISSUE THREAD

**Issue by akshitmahajan** [openskies-sh/aerobridge#14]
![Screen Shot 2021-06-16 at 1 57 22 PM](https://user-images.githubusercontent.com/6078058/122194253-e536b380-ceb2-11eb-8e77-62ca3891ac84.png)
![Screen Shot 2021-06-16 at 1 50 54 PM](https://user-images.githubusercontent.com/6078058/122194261-e831a400-ceb2-11eb-929a-90509fc0dd36.png)
![Screen Shot 2021-06-16 at 2 24 08 PM](https://user-images.githubusercontent.com/6078058/122194310-f253a280-ceb2-11eb-951d-71f1a9bfb9d5.png)

**Comment by hrishiballal** [comment]
Thanks for this, I have now added cancel button to all pages see [commit here](https://github.com/openskies-sh/aerobridge/commit/de8956525386afb5e36431f4ca58dd5df0f5b0bb)
