### ISSUE TITLE
AERO_UI_TC19 : Operators >> Operators >> Add a Operator - Special characters and character limit validations missing

### ISSUE THREAD

**Issue by akshitmahajan** [openskies-sh/aerobridge#15]
![Screen Shot 2021-06-16 at 3 26 33 PM](https://user-images.githubusercontent.com/6078058/122199007-4a8ca380-ceb7-11eb-90cf-6db77a37b49e.png)

**Comment by hrishiballal** [comment]
I have now added a [validator](https://github.com/openskies-sh/aerobridge/blob/master/registry/models.py#L30) to the models and should now prevent this. It might need some tweaking but the first pass is now in.
