### ISSUE TITLE
AERO_UI_TC20 : Operators >> Activities >> Update Activity - Getting 405 Method Not Allowed

### ISSUE THREAD

**Issue by akshitmahajan** [openskies-sh/aerobridge#16]
![Screen Shot 2021-06-16 at 4 21 42 PM](https://user-images.githubusercontent.com/6078058/122207253-904d6a00-cebf-11eb-96ce-58b9c6dbdda1.png)

![Screen Shot 2021-06-16 at 2 23 42 PM](https://user-images.githubusercontent.com/6078058/122207267-93485a80-cebf-11eb-84fd-111f4febba42.png)

**Comment by hrishiballal** [comment]
Thanks I have tested adding new activities, can you check please (I have deployed the new version)
