### ISSUE TITLE
AERO_UI_TC21 : Plans and Opertions >> Plans >> Flight Plan >> Update existing Flight plan - Selecting a past End date or equal to Start date should not be allowed

### ISSUE THREAD

**Issue by akshitmahajan** [openskies-sh/aerobridge#17]
![Screen Shot 2021-06-16 at 4 29 05 PM](https://user-images.githubusercontent.com/6078058/122209557-47e37b80-cec2-11eb-88c3-60ecdb68d5d0.png)
![Screen Shot 2021-06-16 at 1 50 54 PM](https://user-images.githubusercontent.com/6078058/122209562-4914a880-cec2-11eb-8f03-f1d6b1c7341a.png)

**Comment by hrishiballal** [comment]
This is now fixed: 
![image](https://user-images.githubusercontent.com/1588744/122763361-2570aa00-d296-11eb-8efa-3659aadd626d.png), added checks in the serializer and also the form.
